name: koogwz_mobile
description: Koogwe - Application de VTC pour le marché togolais
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  # Maps
  google_maps_flutter: ^2.14.0
  flutter_polyline_points: ^3.1.0

  # Location
  geolocator: ^13.0.0

  # HTTP & API
  http: ^1.2.0

  # Socket
  socket_io_client: ^3.1.4

  # Storage
  shared_preferences: ^2.2.2

  # Launcher
  url_launcher: ^6.2.0
  location: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1  # ✅ Pour générer les icônes de l'app

flutter:
  uses-material-design: true

  # ✅ Assets - Logo de l'application
  assets:
    - assets/icon/logo.png

    
  # Fonts - Télécharge Poppins depuis Google Fonts et place dans assets/fonts/
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Poppins-ExtraBold.ttf
  #         weight: 800

# ✅ Configuration pour générer automatiquement les icônes Android
flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/koogwe_logo.png"
  adaptive_icon_background: "#FFFFFF"  # Fond blanc
  adaptive_icon_foreground: "assets/icon/koogwe_logo.png"