name: koogwz_mobile
description: Koogwz - Application de VTC pour le marché togolais
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  # Maps
  google_maps_flutter: ^2.14.0
  flutter_polyline_points: ^3.1.0

  # Location
  geolocator: ^13.0.0

  # HTTP & API
  http: ^1.2.0

  # Socket
  socket_io_client: ^3.1.4

  # Storage
  shared_preferences: ^2.2.2

  # Launcher
  url_launcher: ^6.2.0
  location: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Fonts - Télécharge Poppins depuis Google Fonts et place dans assets/fonts/
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Poppins-ExtraBold.ttf
  #         weight: 800
